/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActiveComponent: typeof import('./src/components/developer-ui/ActiveComponent.vue')['default']
    AutoReload: typeof import('./src/components/developer-ui/AutoReload.vue')['default']
    Button: typeof import('./src/components/base/Button.vue')['default']
    Check: typeof import('./src/components/icons/Check.vue')['default']
    Close: typeof import('./src/components/icons/Close.vue')['default']
    Column: typeof import('./src/components/layout/Column.vue')['default']
    Container: typeof import('./src/components/layout/Container.vue')['default']
    Content: typeof import('./src/components/layout/Content.vue')['default']
    CustomConsoleLog: typeof import('./src/components/developer-ui/CustomConsoleLog.vue')['default']
    Icon: typeof import('./src/components/icons/Icon.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    Link: typeof import('./src/components/base/Link.vue')['default']
    Nav: typeof import('./src/components/layout/Nav.vue')['default']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RefreshPage: typeof import('./src/components/icons/RefreshPage.vue')['default']
    RefreshPageButton: typeof import('./src/components/developer-ui/RefreshPageButton.vue')['default']
    ReloadOff: typeof import('./src/components/icons/ReloadOff.vue')['default']
    ReloadOn: typeof import('./src/components/icons/ReloadOn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./src/components/layout/Row.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    StudyUI: typeof import('./src/components/study-ui/StudyUI.vue')['default']
    Theme: typeof import('./src/components/layout/Theme.vue')['default']
    Title: typeof import('./src/components/base/Title.vue')['default']
  }
}
